name: CTSound 2
favicon: null
layout_spectrum: 0.007562107173725963
typography_spectrum: 0.2459005976561457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24850097810849547
  lightness: 0.7150021104607731
  saturation: 0.19736044225282967
  rhythmicContrast: 0.5070722957607359
purpose: []
